=== ClausKlein/OSSIE/platform/dtd/deviceconfiguration.dtd
<!ELEMENT deviceconfiguration
	( description?
	, devicemanagersoftpkg
	, componentfiles?
	, partitioning?
	, domainmanager
	, connections?
	, filesystemnames?
	)>
<!ATTLIST deviceconfiguration
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT devicemanagersoftpkg
	( localfile
	)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id 		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, deployondevice?
	, compositepartofdevice?
	, devicepkgfile?
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT deployondevice  EMPTY>
<!ATTLIST deployondevice
	refid		CDATA	#REQUIRED>

<!ELEMENT compositepartofdevice  EMPTY>
<!ATTLIST compositepartofdevice
	refid		CDATA	#REQUIRED>

<!ELEMENT devicepkgfile 
	(localfile
	)>
<!ATTLIST devicepkgfile
	type		CDATA	#IMPLIED>

<!ELEMENT componentinstantiation
	( usagename?
	 ,componentproperties?
	)>
<!ATTLIST componentinstantiation
	id	ID 	#REQUIRED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid	CDATA	#REQUIRED>

<!ELEMENT domainmanager
	( namingservice
	| stringifiedobjectref
	)>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT filesystemnames
	(filesystemname+
	)>

<!ELEMENT filesystemname EMPTY>
<!ATTLIST filesystemname
	mountname	CDATA	#REQUIRED
	deviceid	CDATA	#REQUIRED>

<!ELEMENT connections
      ( connectinterface*
      )>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>

<!ATTLIST connectinterface
	id		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | findby
	  )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

=== ClausKlein/OSSIE/platform/nodes/default_GPP_USRP_sound_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration SYSTEM "../../xml/dtd/deviceconfiguration.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<deviceconfiguration name="DeviceManager" id="DCE:26555f88-e859-11db-97b9-00123f573a7f">
    <devicemanagersoftpkg>
        <localfile name="DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions--> 
        <componentfile type="SPD" id="GPP1_51b862bc-d95c-11db-8b8d-00123f573a7f">
            <localfile name="xml/GPP/GPP.spd.xml"/>
        </componentfile>
        <componentfile type="SPD" id="USRP1_7c322634-e859-11db-8ffa-00123f573a7f">
            <localfile name="xml/USRP/USRP.spd.xml"/>
        </componentfile>
        <componentfile type="SPD" id="32d3bc8c-13e2-11dc-be81-00123f63025f">
            <localfile name="xml/soundCardCapture/soundCardCapture.spd.xml"/>
        </componentfile>
        <componentfile type="SPD" id="32555252-13e2-11dc-94ec-00123f63025f">
            <localfile name="xml/soundCardPlayback/soundCardPlayback.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="GPP1_51b862bc-d95c-11db-8b8d-00123f573a7f"/>
            <componentinstantiation id="DCE:5ba336ee-aaaa-aaaa-aaaa-00123f573a7f">
                <usagename>GPP1</usagename> 
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="USRP1_7c322634-e859-11db-8ffa-00123f573a7f"/>
            <componentinstantiation id="DCE:5ba336ee-bbbb-bbbb-bbbb-00123f573a7f">
                <usagename>USRP1</usagename> 
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="32d3bc8c-13e2-11dc-be81-00123f63025f"/>
            <componentinstantiation id="DCE:459811e2-cccc-cccc-cccc-00123f63025f">
                <usagename>soundCardCapture1</usagename> 
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="32555252-13e2-11dc-94ec-00123f63025f"/>
            <componentinstantiation id="DCE:4598fa94-dddd-dddd-dddd-00123f63025f">
                <usagename>soundCardPlayback1</usagename> 
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>

=== ClausKlein/OSSIE/platform/nodes/default_GPP_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration SYSTEM "../../xml/dtd/deviceconfiguration.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<deviceconfiguration name="DeviceManager" id="DCE:6bba314a-d95c-11db-a834-00123f573a7f">
    <devicemanagersoftpkg>
        <localfile name="DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions--> 
        <componentfile type="SPD" id="GPP1_51b862bc-d95c-11db-8b8d-00123f573a7f">
            <localfile name="/xml/GPP/GPP.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="GPP1_51b862bc-d95c-11db-8b8d-00123f573a7f"/>
            <componentinstantiation id="DCE:5ba336ee-aaaa-aaaa-aaaa-00123f573a7f">
                <usagename>GPP1</usagename> 
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>

=== ClausKlein/OSSIE/platform/nodes/default_GPP_sound_node/DeviceManager.dcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deviceconfiguration SYSTEM "../../xml/dtd/deviceconfiguration.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.2-->
<!--Powered by Python-->
<deviceconfiguration id="DCE:2607c0a6-c54f-11dc-8920-000c29a1ba37" name="DeviceManager">
    <devicemanagersoftpkg>
        <localfile name="DeviceManager.spd.xml"/>
    </devicemanagersoftpkg>
    <componentfiles>
        <!--Device Definitions-->
        <componentfile id="soundCardPlayback1_990f5720-c546-11dc-bf44-000c29a1ba37" type="SPD">
            <localfile name="/xml/soundCardPlayback/soundCardPlayback.spd.xml"/>
        </componentfile>
        <componentfile type="SPD" id="32d3bc8c-13e2-11dc-be81-00123f63025f">
            <localfile name="xml/soundCardCapture/soundCardCapture.spd.xml"/>
        </componentfile>
        <componentfile id="GPP1_98faff14-c546-11dc-afee-000c29a1ba37" type="SPD">
            <localfile name="/xml/GPP/GPP.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="soundCardPlayback1_990f5720-c546-11dc-bf44-000c29a1ba37"/>
            <componentinstantiation id="DCE:25f6dfa2-c54f-11dc-b355-000c29a1ba37">
                <usagename>soundCardPlayback1</usagename>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="32d3bc8c-13e2-11dc-be81-00123f63025f"/>
            <componentinstantiation id="DCE:459811e2-cccc-cccc-cccc-00123f63025f">
                <usagename>soundCardCapture1</usagename>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="GPP1_98faff14-c546-11dc-afee-000c29a1ba37"/>
            <componentinstantiation id="DCE:5ba336ee-aaaa-aaaa-aaaa-00123f573a7f">
                <usagename>GPP1</usagename>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <domainmanager>
        <namingservice name="DomainName1/DomainManager"/>
    </domainmanager>
</deviceconfiguration>
