=== ClausKlein/OSSIE/platform/dtd/properties.dtd
<!ELEMENT properties
     	 ( description?
     	 , 	( simple
		| simplesequence
		| test
		| struct
		| structsequence)+
       )> 

<!ELEMENT simple 
	( description?
	, value?
	, units?
	, range?
	, enumerations?
	, kind*
	, action?
	)>
<!ATTLIST simple
	id	ID							#REQUIRED
	type	( boolean	| char	| double | float
		| short	| long	| objref | octet
		| string	| ulong	| ushort )		#REQUIRED
	name	CDATA							#IMPLIED
	mode	( readonly	| readwrite | writeonly)	"readwrite">

<!ELEMENT description (#PCDATA)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT units (#PCDATA)>

<!ELEMENT range EMPTY>
<!ATTLIST range
	min		CDATA	#REQUIRED
	max		CDATA	#REQUIRED>

<!ELEMENT enumerations
	( enumeration+
	)>

<!ELEMENT enumeration EMPTY>
<!ATTLIST enumeration
	label		CDATA	#REQUIRED
	value		CDATA	#IMPLIED>

<!ELEMENT kind EMPTY>
<!ATTLIST kind
	kindtype	(allocation | configure | test | execparam | factoryparam) 
"configure">

<!ELEMENT action EMPTY>
<!ATTLIST action
	type	( eq  | ne | gt  |  lt | ge | le | external ) "external">

<!ELEMENT simplesequence 
	( description?
	, values?
	, units?
	, range?
	, kind*
	, action?
	)>
<!ATTLIST simplesequence
	id	ID						#REQUIRED
	type  ( boolean | char   | double | float
	      | short  | long   | objref | octet
	      | string | ulong  | ushort )		#REQUIRED
	name	CDATA						#IMPLIED
	mode	(readonly | readwrite | writeonly)	"readwrite">

<!ELEMENT values
	( value+ 
	)>

<!ELEMENT test 
	( description
      , inputValue?
	, resultValue
	)>
<!ATTLIST test
	id		CDATA #REQUIRED>

<!ELEMENT inputValue
	( simple+
	)>

<!ELEMENT resultValue
	( simple+
	)>

<!ELEMENT struct 
	( description?
	, simple+
	, configurationkind?
	)>
<!ATTLIST struct
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">

<!ELEMENT configurationkind EMPTY>
<!ATTLIST configurationkind
	kindtype	(configure | factoryparam)	"configure">

<!ELEMENT structsequence
	( description?
	, structvalue+
	, configurationkind?
	)>
<!ATTLIST structsequence
	id       	ID	#REQUIRED
	structrefid CDATA	#REQUIRED
	name		CDATA	#IMPLIED
	mode		(readonly | readwrite | writeonly)  "readwrite">
		
<!ELEMENT structvalue
	(simpleref+	        
	)>
		
<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid 	CDATA	#REQUIRED
	value 	CDATA	#REQUIRED>

=== ClausKlein/OSSIE/components/ChannelDemo/ChannelDemo.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "../dtd/properties.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<properties>
    <simple id="DCE:a337c5f0-8245-11dc-860f-00123f63025f" mode="readonly" name="noise_std_dev" type="short">
        <value>1000</value> 
        <description>Standard deviation of noise</description> 
        <kind kindtype="configure"/>
    </simple>
    <simple id="DCE:1c4a3eb9-9e3a-4c20-849a-90c6eaef9e5a" mode="readonly" name="phase_offset" type="float">
        <value>0</value> 
        <description>Phase offset (degrees)</description> 
        <kind kindtype="configure"/>
    </simple>
</properties>

=== ClausKlein/OSSIE/components/amplifier/amplifier.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "../dtd/properties.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<properties>
    <simple type="float" id="DCE:06b88d4f-dd38-44e6-bc49-82db0eba5bc6" name="I_gain" mode="readonly">
        <description>Gain for the I channel.  Linear.</description> 
        <value>1</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:df91b1a8-9c83-44b4-bf2c-0dbeacb2b6f4" name="Q_gain" mode="readonly">
        <description>Gain for the Q channel.  Linear.</description> 
        <value>1</value> 
        <kind kindtype="configure"/>
    </simple>
</properties>

=== ClausKlein/OSSIE/components/USRP_Commander/xml/USRP_Commander.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "../dtd/properties.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.5.0b-->
<!--Powered by Python-->
<properties>
    <simple type="float" id="DCE:3efc3930-2739-40b4-8c02-ecfb1b0da9ee" name="rx_rreq" mode="readwrite">
        <description>Receiver Frequency</description> 
        <value>0</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:6a2d6952-ca11-4787-afce-87a89b882b7b" name="tx_freq" mode="readwrite">
        <description>Transmitter Frequency</description> 
        <value>0</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="short" id="DCE:9ca12c0e-ba65-40cf-9ef3-6e7ac671ab5d" name="tx_interp" mode="readonly">
        <description>Transmitter Interpolation Factor</description> 
        <value>512</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="short" id="DCE:92ec2b80-8040-47c7-a1d8-4c9caa4a4ed2" name="rx_decim" mode="readwrite">
        <description>Receiver Decimation Factor</description> 
        <value>256</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="ulong" id="DCE:93324adf-14f6-4406-ba92-a3650089857f" name="rx_size" mode="readonly">
        <description>Receiver Data Packet Size</description> 
        <value>8192</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:99d586b6-7764-4dc7-83fa-72270d0f1e1b" name="rx_gain" mode="readwrite">
        <description>Receiver Gain</description>  
        <value>0</value>   
        <kind kindtype="configure"/> 
    </simple>
    <simple type="short" id="DCE:2d9c5ee4-a6f3-4ab9-834b-2b5c95818e53" name="rx_gain_max" mode="readwrite">
        <description>If 1 sets the RX Gain to max. If set to 1, the Receiver Gain property is ignored</description>  
        <value>1</value>   
        <kind kindtype="configure"/> 
    </simple>
    <simple type="short" id="DCE:0a9b8c8c-f130-4a8f-9ef8-bba023128a4b" name="tx_start" mode="readonly">
        <description>Start the transmitter when the component starts</description> 
        <value>0</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="short" id="DCE:fd42344f-4d87-465b-9e6f-e1d7ae48afd6" name="rx_start" mode="readonly">
        <description>Start the receiver when the component starts</description> 
        <value>1</value> 
        <kind kindtype="configure"/>
    </simple>
</properties>

=== ClausKlein/OSSIE/components/Decimator/Decimator.prf.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE properties SYSTEM "../dtd/properties.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<properties>
    <description />
    <simple id="DCE:cea26b54-9d86-4b68-a761-14186efa9415" type="ushort" name="DecimateBy" mode="readwrite">
        <value>1</value>
        <kind kindtype="configure" />
    </simple>
    <simplesequence id="DCE:134e5dd8-c773-47af-a557-2837076358c4" type="float" name="filter" mode="readwrite">
        <values>
            <value>1</value>
        </values>
        <kind kindtype="configure" />
    </simplesequence>
</properties>

=== ClausKlein/OSSIE/components/AutomaticGainControl/xml/AutomaticGainControl.prf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "../dtd/properties.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<properties>
    <simple type="float" id="DCE:aaf97fa0-d184-4d88-9954-3a1334c73d6d" name="energy_lo" mode="readwrite">
        <description>low energy threshold</description> 
        <value>4000</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:346e17c9-6678-483a-bffb-1909c64bddc0" name="energy_hi" mode="readwrite">
        <description>high energy threshold</description> 
        <value>4000</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:4608b943-4fe2-49df-91fb-afa287b609d4" name="k_attack" mode="readwrite">
        <description>attack time constant</description> 
        <value>0.002</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:491ec3de-ed45-48af-a6fc-ca2d6465e136" name="k_release" mode="readwrite">
        <description>release time constant</description> 
        <value>0.0005</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:312f63fe-709a-4217-933b-c584c8d6a9bb" name="g_min" mode="readwrite">
        <description>minimum gain value</description> 
        <value>1</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:8357ee0d-2417-46d9-8475-2e5778d797e4" name="g_max" mode="readwrite">
        <description>maximum gain value</description> 
        <value>100.0</value> 
        <kind kindtype="configure"/>
    </simple>
    <simple type="float" id="DCE:b9b72ec8-d0bd-4060-b356-dcc6b0809e65" name="rssi_pass" mode="readwrite">
        <description>Received signal strength level above which data will be passed</description> 
        <value>1000</value>
        <kind kindtype="configure"/>
    </simple>
</properties>
