=== ClausKlein/OSSIE/platform/dtd/softwarecomponent.dtd
<!ELEMENT softwarecomponent
	( corbaversion
	, componentrepid
	, componenttype
	, componentfeatures
	, interfaces
	, propertyfile?
	)>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT corbaversion (#PCDATA)> 

<!ELEMENT componentrepid EMPTY>
<!ATTLIST componentrepid
	repid		CDATA	#REQUIRED>

<!ELEMENT componenttype (#PCDATA)>

<!ELEMENT componentfeatures
	( supportsinterface* 
	, ports
	)>

<!ELEMENT supportsinterface EMPTY>
<!ATTLIST supportsinterface
	repid			CDATA	#REQUIRED
 	supportsname	CDATA	#REQUIRED>

<!ELEMENT ports
	(provides   
	| uses
	)*> 

<!ELEMENT provides
	( porttype*)>
<!ATTLIST provides
	repid			CDATA	#REQUIRED
	providesname	CDATA	#REQUIRED>

<!ELEMENT uses
	( porttype*)>
<!ATTLIST uses
	repid		CDATA	#REQUIRED
	usesname	CDATA	#REQUIRED>

<!ELEMENT porttype EMPTY>
<!ATTLIST porttype
    	type	( data | control | responses	| test ) 	#REQUIRED>

<!ELEMENT interfaces
	( interface+ 
	)>

<!ELEMENT interface
	( inheritsinterface*)>
<!ATTLIST interface
	repid		CDATA	#REQUIRED
	name		CDATA	#REQUIRED>

<!ELEMENT inheritsinterface EMPTY>
<!ATTLIST inheritsinterface
	repid		CDATA	#REQUIRED>

=== ClausKlein/OSSIE/tools/WaveDev/wavedev/generate/basic_xml/DomainManager.scd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarecomponent SYSTEM "../../xml/dtd/softwarecomponent.dtd">
<softwarecomponent>
	<corbaversion>2.2</corbaversion>
	<componentrepid repid="IDL:CF/DomainManager:1.0"/>
	<componenttype>domainmanager</componenttype>
	<componentfeatures>
		<supportsinterface repid="IDL:CF/DomainManager:1.0" supportsname="DomainManager"/>
		<supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet"/>
	</componentfeatures>
	<interfaces>
		<interface repid="IDL:CF/DomainManager:1.0" name="DomainManager">
			<inheritsinterface repid="IDL:CF/PropertySet:1.0"/>
		</interface>
		<interface repid="IDL:CF/PropertySet:1.0" name="PropertySet"/>
	</interfaces>
</softwarecomponent>

=== ClausKlein/OSSIE/platform/GPP/GPP.scd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/ExecutableDevice:1.0" />
    <componenttype>executabledevice</componenttype>
    <componentfeatures>
        <supportsinterface repid="IDL:CF/ExecutableDevice:1.0" supportsname="ExecutableDevice" />
        <supportsinterface repid="IDL:CF/Device:1.0" supportsname="Device" />
        <supportsinterface repid="IDL:CF/LoadableDevice:1.0" supportsname="LoadableDevice" />
        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
        <ports />
    </componentfeatures>
    <interfaces>
        <interface repid="IDL:CF/ExecutableDevice:1.0" name="ExecutableDevice">
            <!--[Inherited interface IDL:CF/Device:1.0]-->
            <inheritsinterface repid="IDL:CF/Device:1.0" />
            <!--[Inherited interface IDL:CF/LoadableDevice:1.0]-->
            <inheritsinterface repid="IDL:CF/LoadableDevice:1.0" />
            <!--[Inherited interface IDL:CF/Resource:1.0]-->
            <inheritsinterface repid="IDL:CF/Resource:1.0" />
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
        </interface>
    </interfaces>
</softwarecomponent>

=== ClausKlein/OSSIE/components/pass_data/pass_data.scd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.2-->
<!--Powered by Python-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion> 
    <componentrepid repid="IDL:CF/Resource:1.0"/>
    <componenttype>resource</componenttype> 
    <componentfeatures>
        <supportsinterface supportsname="Resource" repid="IDL:CF/Resource:1.0"/>
        <supportsinterface supportsname="LifeCycle" repid="IDL:CF/LifeCycle:1.0"/>
        <supportsinterface supportsname="PortSupplier" repid="IDL:CF/PortSupplier:1.0"/>
        <supportsinterface supportsname="PropertySet" repid="IDL:CF/PropertySet:1.0"/>
        <supportsinterface supportsname="TestableObject" repid="IDL:CF/TestableObject:1.0"/>
        <ports>
            <provides providesname="cshort_in" repid="IDL:standardInterfaces/complexShort:1.0">
                <porttype type="data"/>
            </provides>

            <uses usesname="cshort_out" repid="IDL:standardInterfaces/complexShort:1.0">
                <porttype type="data"/>
            </uses>

            <uses usesname="send_timing_report" repid="IDL:customInterfaces/timingStatus:1.0">
                <porttype type="data"/>

            </uses>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface name="Resource" repid="IDL:CF/Resource:1.0">
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]--> 
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0"/>
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]--> 
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0"/>
            <!--[Inherited interface IDL:CF/PropertySet:1.0]--> 
            <inheritsinterface repid="IDL:CF/PropertySet:1.0"/>
            <!--[Inherited interface IDL:CF/TestableObject:1.0]--> 
            <inheritsinterface repid="IDL:CF/TestableObject:1.0"/>
        </interface>
        <interface name="timingStatus" repid="IDL:customInterfaces/timingStatus:1.0"/>

        <interface name="complexShort" repid="IDL:standardInterfaces/complexShort:1.0"/>
    </interfaces>
</softwarecomponent>

=== ClausKlein/OSSIE/components/Decimator/Decimator.scd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/Resource:1.0" />
    <componenttype>resource</componenttype>
    <componentfeatures>
        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
        <ports>
            <provides repid="IDL:standardInterfaces/complexShort:1.0" providesname="inData">
                <porttype type="data" />
            </provides>
            <uses repid="IDL:standardInterfaces/complexShort:1.0" usesname="outData">
                <porttype type="data" />
            </uses>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface repid="IDL:standardInterfaces/complexShort:1.0" name="complexShort" />
        <interface repid="IDL:CF/Resource:1.0" name="Resource">
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
        </interface>
    </interfaces>
    <propertyfile>
        <localfile name="Decimator.prf.xml" />
    </propertyfile>
</softwarecomponent>

=== ClausKlein/OSSIE/platform/USRP/xml/USRP.scd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/Device:1.0" />
    <componenttype>device</componenttype>
    <componentfeatures>
        <supportsinterface repid="IDL:CF/Device:1.0" supportsname="Device" />
        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
        <ports>
            <provides repid="IDL:standardInterfaces/TX_Control:1.0" providesname="TX_Control">
                <porttype type="control" />
            </provides>
            <provides repid="IDL:standardInterfaces/RX_Control:1.0" providesname="RX_Control">
                <porttype type="control" />
            </provides>
            <provides repid="IDL:standardInterfaces/complexShort:1.0" providesname="TX_Data">
                <porttype type="data" />
            </provides>
            <uses repid="IDL:standardInterfaces/complexShort:1.0" usesname="RX_Data_1">
                <porttype type="data" />
            </uses>
            <uses repid="IDL:standardInterfaces/complexShort:1.0" usesname="RX_Data_2">
                <porttype type="data" />
            </uses>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface repid="IDL:standardInterfaces/complexShort:1.0" name="complexShort" />
        <interface repid="IDL:CF/Device:1.0" name="Device">
            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
            <!--[Inherited interface IDL:CF/Resource:1.0]-->
            <inheritsinterface repid="IDL:CF/Resource:1.0" />
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
        </interface>
        <interface repid="IDL:standardInterfaces/TX_Control:1.0" name="TX_Control" />
        <interface repid="IDL:standardInterfaces/RX_Control:1.0" name="RX_Control" />
    </interfaces>
</softwarecomponent>

=== ClausKlein/OSSIE/components/WebCamCapture/WebCamCapture.scd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion> 
    <componentrepid repid="IDL:CF/Resource:1.0"/>
    <componenttype>resource</componenttype> 
    <componentfeatures>
        <supportsinterface supportsname="Resource" repid="IDL:CF/Resource:1.0"/>
        <supportsinterface supportsname="LifeCycle" repid="IDL:CF/LifeCycle:1.0"/>
        <supportsinterface supportsname="PortSupplier" repid="IDL:CF/PortSupplier:1.0"/>
        <supportsinterface supportsname="PropertySet" repid="IDL:CF/PropertySet:1.0"/>
        <supportsinterface supportsname="TestableObject" repid="IDL:CF/TestableObject:1.0"/>
        <ports>
            <uses usesname="JPEG_DataOut" repid="IDL:standardInterfaces/realChar:1.0">
                <porttype type="data"/>
            </uses>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface name="Resource" repid="IDL:CF/Resource:1.0">
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]--> 
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0"/>
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]--> 
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0"/>
            <!--[Inherited interface IDL:CF/PropertySet:1.0]--> 
            <inheritsinterface repid="IDL:CF/PropertySet:1.0"/>
            <!--[Inherited interface IDL:CF/TestableObject:1.0]--> 
            <inheritsinterface repid="IDL:CF/TestableObject:1.0"/>
        </interface>
        <interface name="realChar" repid="IDL:standardInterfaces/realChar:1.0"/>
    </interfaces>
</softwarecomponent>

=== ClausKlein/OSSIE/platform/Sound_out/soundCardPlayback.scd.xml
<?xml version="1.0" encoding="us-ascii"?>
	<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
	<!--
	    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
	    http://www.zeligsoft.com
	-->
	<softwarecomponent>
	    <corbaversion>2.2</corbaversion>
	    <componentrepid repid="IDL:CF/Device:1.0" />
 	    <componenttype>device</componenttype>
 	    <componentfeatures>
 	        <supportsinterface repid="IDL:CF/Device:1.0" supportsname="Device" />
 	        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
 	        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
 	        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
 	        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
 	        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
 	        <ports>
 	            <provides repid="IDL:standardInterfaces/complexShort:1.0" providesname="soundOut">
 	                <porttype type="data" />
 	            </provides>
 	            <provides repid="IDL:standardInterfaces/audioInControl:1.0" providesname="soundInControl">
 	                <porttype type="control" />
 	            </provides>
 	            <provides repid="IDL:standardInterfaces/audioOutControl:1.0" providesname="soundOutControl">
 	                <porttype type="control" />
 	            </provides>
 	            <uses repid="IDL:StdInterfaces/AudioPort:1.0" usesname="soundIn">
 	                <porttype type="control" />
 	            </uses>
 	        </ports>
 	    </componentfeatures>
 	    <interfaces>
 	        <interface repid="IDL:StdInterfaces/AudioPort:1.0" name="AudioPort" />
 	        <interface repid="IDL:CF/Device:1.0" name="Device">
 	            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
 	            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
 	            <!--[Inherited interface IDL:CF/Resource:1.0]-->
 	            <inheritsinterface repid="IDL:CF/Resource:1.0" />
 	            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
 	            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
 	            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
 	            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
 	            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
 	            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
 	        </interface>
 	        <interface repid="IDL:standardInterfaces/audioInControl:1.0" name="audioInControl" />
 	        <interface repid="IDL:standardInterfaces/audioOutControl:1.0" name="audioOutControl" />
 	    </interfaces>
	</softwarecomponent>
