=== ClausKlein/OSSIE/platform/dtd/softpkg.dtd
<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( propertyref+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

=== ClausKlein/OSSIE/platform/USRP/xml/USRP.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softpkg id="DCE:1d9783ae-677d-4150-887e-3d56761d4c37" name="USRP" type="sca_compliant" version="">
    <title />
    <description>Universal software radio peripheral</description>
    <author>
        <name>Ossie Team</name>
        <company>Va Tech/MPRG</company>
        <webpage>http://ossie.mprg.org/</webpage>
    </author>
    <descriptor name="">
        <localfile name="xml/USRP/USRP.scd.xml" />
    </descriptor>
    <!--[Implementation USRPImplementation_linux]-->
    <implementation id="DCE:005a01c3-e469-4332-a4bd-a83b0159853e" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="bin/USRP" />
        </code>
        <os name="Linux" version="5.5.1" />
        <processor name="x86" />
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/USRP_Commander/xml/USRP_Commander.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="USRP_Commander" id="DCE:20f9d65a-7f38-48ce-87cf-d106b34be02a">
    <title>USRP commander</title>
    <description>Controller for the USRP device, both transmit and receive</description>
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/USRP_Commander/USRP_Commander.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/USRP_Commander/USRP_Commander.scd.xml"/>
    </descriptor>
    <implementation id="DCE:00e84b76-1c47-4b87-8ebc-50459c8a5c43" aepcompliance="aep_compliant">
        <description>Default implementation description</description> 
        <code type="Executable">
            <localfile name="bin/USRP_Commander"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/WebCamCapture/WebCamCapture.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="WebCamCapture" id="DCE:7385d79e-c124-11db-b9e3-000129227a88">
    <title/>
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/WebCamCapture/WebCamCapture.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/WebCamCapture/WebCamCapture.scd.xml"/>
    </descriptor>
    <implementation id="DCE:7386a14c-c124-11db-b6c8-000129227a88" aepcompliance="aep_compliant">
        <description>Default Description</description> 
        <code type="Executable">
            <localfile name="bin/WebCamCapture"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/WFMDemod/WFMDemod.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.2-->
<!--Powered by Python-->
<softpkg id="DCE:7674ce46-e1a4-11dc-b82c-000c290e5893" name="WFMDemod">
    <title/>
    <description>FM Demodulator</description> 
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/WFMDemod/WFMDemod.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/WFMDemod/WFMDemod.scd.xml"/>
    </descriptor>
    <implementation id="DCE:7679e4b2-e1a4-11dc-9c98-000c290e5893">
        <description>Description</description> 
        <code type="Executable">
            <localfile name="bin/WFMDemod"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/ChannelDemo/ChannelDemo.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg id="DCE:ac534fb0-8245-11dc-85c9-00123f63025f" name="ChannelDemo">
    <title/>
    <description>Adds white Gaussian noise to a signal</description> 
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/ChannelDemo/ChannelDemo.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/ChannelDemo/ChannelDemo.scd.xml"/>
    </descriptor>
    <implementation id="DCE:ac54cfa2-8245-11dc-afb5-00123f63025f">
        <description>Linux implementation</description> 
        <code type="Executable">
            <localfile name="bin/ChannelDemo"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/Decimator/Decimator.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softpkg id="DCE:66a59f6f-e26a-412f-959b-7bcc383a80be" name="Decimate" type="sca_compliant" version="">
    <title>Decimator component, version 0.6.2</title>
    <description>Sample rate reduction by efficiently filtering and subsampling, v0.6.2</description>
    <author>
        <name>OSSIE Team</name>
        <company>Mobile and Portable Radio Research Group</company>
        <webpage>http://www.mprg.org</webpage>
    </author>
    <propertyfile type="PRF">
      <localfile name="xml/Decimator/Decimator.prf.xml" />
    </propertyfile>
    <descriptor name="">
        <localfile name="xml/Decimator/Decimator.scd.xml" />
    </descriptor>
    <!--[Implementation Decimate_linux]-->
    <implementation id="DCE:1aee5bc6-5149-4c58-a2ae-89fab9276719" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="bin/Decimator" />
        </code>
        <os name="Linux" version="5.5.1" />
        <processor name="x86" />
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/RxDemo/RxDemo.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg id="DCE:5e399696-8249-11dc-9442-00123f63025f" name="RxDemo">
    <title/>
    <description>Receives and compares data generated by TxDemo; displays errors</description> 
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/RxDemo/RxDemo.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/RxDemo/RxDemo.scd.xml"/>
    </descriptor>
    <implementation id="DCE:5e3ad966-8249-11dc-a466-00123f63025f">
        <description>Linux implementation</description> 
        <code type="Executable">
            <localfile name="bin/RxDemo"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/tools/WaveDev/wavedev/generate/basic_xml/DomainManager.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../../xml/dtd/softpkg.dtd">
<softpkg id="DCE:82f6515a-de05-47f0-8e7a-1c9f621c00ee" name="DomainManager">
	<descriptor>
		<localfile name="DomainManager.scd.xml"/>
	</descriptor>
	<implementation id="DCE:d3e8aba5-4421-45c5-9be6-372b763883e7">
		<description>implementation of a Domain Manager</description>
		<code type="Executable">
			<localfile name="/domainmanager.exe"/>
			<entrypoint>domainmanager.exe</entrypoint>
		</code>
		<compiler name="msvc" version="6.0"/>
		<programminglanguage name="c++"/>
		<processor name="x86"/>
		<os name="WinNT" version="5.0"/>
	</implementation>
</softpkg>
