=== ClausKlein/OSSIE/platform/dtd/softpkg.dtd
<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( propertyref+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

=== ClausKlein/OSSIE/components/TxDemo/TxDemo.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg id="DCE:23ecc262-8242-11dc-9d05-00123f63025f" name="TxDemo">
    <title/>
    <description>This component generates QPSK symbols</description> 
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/TxDemo/TxDemo.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/TxDemo/TxDemo.scd.xml"/>
    </descriptor>
    <implementation id="DCE:23ed8652-8242-11dc-aba9-00123f63025f">
        <description>Linux implementation</description> 
        <code type="Executable">
            <localfile name="bin/TxDemo"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>
