=== ClausKlein/OSSIE/platform/dtd/softwareassembly.dtd
<!ELEMENT softwareassembly
	( description?
	, componentfiles
	, partitioning
	, assemblycontroller
	, connections?
	, externalports?
	)>
<!ATTLIST softwareassembly
	id		ID	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT componentfiles 
	( componentfile+
	)>

<!ELEMENT componentfile
	( localfile 
	)>
<!ATTLIST componentfile
	id		ID	#REQUIRED
	type		CDATA	#IMPLIED>

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT partitioning 
	( componentplacement
	|  hostcollocation
	)*>

<!ELEMENT componentplacement 
	( componentfileref
	, componentinstantiation+
	)>

<!ELEMENT componentfileref  EMPTY>
<!ATTLIST componentfileref
	refid		CDATA	#REQUIRED>

<!ELEMENT componentinstantiation
	( usagename?
	, componentproperties?
	, findcomponent?
	)>
<!ATTLIST componentinstantiation
	id		ID 	#REQUIRED>

<!ELEMENT usagename (#PCDATA)>

<!ELEMENT componentproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT findcomponent
	( componentresourcefactoryref
	| namingservice
	)>

<!ELEMENT componentresourcefactoryref
	( resourcefactoryproperties?
	)>
<!ATTLIST componentresourcefactoryref 
	refid		CDATA	#REQUIRED>

<!ELEMENT devicethatloadedthiscomponentref EMPTY>
<!ATTLIST devicethatloadedthiscomponentref 
	refid		CDATA	#REQUIRED>

<!ELEMENT deviceusedbythiscomponentref EMPTY>
<!ATTLIST deviceusedbythiscomponentref 
	refid		CDATA	#REQUIRED
	usesrefid	CDATA	#REQUIRED>

<!ELEMENT resourcefactoryproperties 
	( simpleref
	| simplesequenceref
	| structref
	| structsequenceref
	)+ >

<!ELEMENT simpleref EMPTY>
<!ATTLIST simpleref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
		
<!ELEMENT simplesequenceref
	(values
	)>
<!ATTLIST simplesequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structref
	(simpleref+        
	)>
<!ATTLIST structref
	refid		CDATA	#REQUIRED>

<!ELEMENT structsequenceref
	( structvalue+
	)>
<!ATTLIST structsequenceref
	refid		CDATA	#REQUIRED>

<!ELEMENT structvalue
	(simpleref+
	)>
		
<!ELEMENT values
	( value+ 
	)>
		
<!ELEMENT value (#PCDATA)>

<!ELEMENT componentinstantiationref EMPTY>
<!ATTLIST componentinstantiationref 
	refid		CDATA	#REQUIRED>

<!ELEMENT findby
	( namingservice
	| stringifiedobjectref
	| domainfinder
	)>

<!ELEMENT namingservice EMPTY>
<!ATTLIST namingservice
	name 		CDATA	#REQUIRED>

<!ELEMENT stringifiedobjectref (#PCDATA)>

<!ELEMENT domainfinder EMPTY>
<!ATTLIST domainfinder
	type		CDATA	#REQUIRED
	name		CDATA	#IMPLIED>

<!ELEMENT hostcollocation
	( componentplacement
	)+>
<!ATTLIST hostcollocation
	id		ID	#IMPLIED
	name		CDATA	#IMPLIED>

<!ELEMENT assemblycontroller
	( componentinstantiationref
	)>

<!ELEMENT connections
	( connectinterface*
	)>

<!ELEMENT connectinterface
	( usesport
	, ( providesport
	  | componentsupportedinterface
	  | findby
	  )
	)>
<!ATTLIST connectinterface
	id 		ID	#IMPLIED>

<!ELEMENT usesport
	( usesidentifier
	, (componentinstantiationref
	   | devicethatloadedthiscomponentref
	   | deviceusedbythiscomponentref
	   | findby
	   )
	)>

<!ELEMENT usesidentifier (#PCDATA)>

<!ELEMENT providesport
	( providesidentifier
	, ( componentinstantiationref
	  | devicethatloadedthiscomponentref
	  | deviceusedbythiscomponentref
	  | findby 
        )
	)>

<!ELEMENT providesidentifier (#PCDATA)>

<!ELEMENT componentsupportedinterface
	( supportedidentifier
	, ( componentinstantiationref
	  | findby
	  )
	)>

<!ELEMENT supportedidentifier (#PCDATA)>

<!ELEMENT externalports 
	(port+
	)>

<!ELEMENT port
	( description?
	, (usesidentifier | providesidentifier | supportedidentifier)
	, componentinstantiationref
	)>

=== ClausKlein/OSSIE/waveforms/ossie_demo/ossie_demo.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly SYSTEM "../../xml/dtd/softwareassembly.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softwareassembly id="DCE:e1a85dc2-824a-11dc-93f8-00123f63025f" name="OSSIE::ossie_demo">
    <componentfiles>
        <componentfile id="TxDemo_8f63a724-824a-11dc-bb02-00123f63025f" type="SPD">
            <localfile name="/xml/TxDemo/TxDemo.spd.xml"/>
        </componentfile>
        <componentfile id="ChannelDemo_8f35b620-824a-11dc-8ba7-00123f63025f" type="SPD">
            <localfile name="/xml/ChannelDemo/ChannelDemo.spd.xml"/>
        </componentfile>
        <componentfile id="RxDemo_8eec63da-824a-11dc-a9bb-00123f63025f" type="SPD">
            <localfile name="/xml/RxDemo/RxDemo.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="TxDemo_8f63a724-824a-11dc-bb02-00123f63025f"/>
            <componentinstantiation id="DCE:9530783a-824a-11dc-9c95-00123f63025f">
                <componentproperties>
                    <simpleref description="" name="packet_delay_ms" refid="DCE:1b9ca208-8242-11dc-9ba3-00123f63025f" value="500"/>
                </componentproperties>
                <usagename>TxDemo1</usagename> 
                <findcomponent>
                    <namingservice name="TxDemo1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="ChannelDemo_8f35b620-824a-11dc-8ba7-00123f63025f"/>
            <componentinstantiation id="DCE:9a75af54-824a-11dc-9a77-00123f63025f">
                <componentproperties>
                    <simpleref description="" name="noise_std_dev" refid="DCE:a337c5f0-8245-11dc-860f-00123f63025f" value="2500"/>
                    <simpleref description="" name="phase_offset" refid="DCE:1c4a3eb9-9e3a-4c20-849a-90c6eaef9e5a" value="10"/>
                </componentproperties>
                <usagename>ChannelDemo1</usagename> 
                <findcomponent>
                    <namingservice name="ChannelDemo1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
        <componentplacement>
            <componentfileref refid="RxDemo_8eec63da-824a-11dc-a9bb-00123f63025f"/>
            <componentinstantiation id="DCE:9c3f3972-824a-11dc-af99-00123f63025f">
                <usagename>RxDemo1</usagename> 
                <findcomponent>
                    <namingservice name="RxDemo1"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:9530783a-824a-11dc-9c95-00123f63025f"/>
    </assemblycontroller>
    <connections>
        <connectinterface id="DCE:e1aa5d66-824a-11dc-adea-00123f63025f">
            <providesport>
                <providesidentifier>samples_in</providesidentifier> 
                <findby>
                    <namingservice name="ChannelDemo1"/>
                </findby>
            </providesport>
            <usesport>
                <usesidentifier>symbols_out</usesidentifier> 
                <findby>
                    <namingservice name="TxDemo1"/>
                </findby>
            </usesport>
        </connectinterface>
        <connectinterface id="DCE:e1ad7154-824a-11dc-85b0-00123f63025f">
            <providesport>
                <providesidentifier>symbols_in</providesidentifier> 
                <findby>
                    <namingservice name="RxDemo1"/>
                </findby>
            </providesport>
            <usesport>
                <usesidentifier>samples_out</usesidentifier> 
                <findby>
                    <namingservice name="ChannelDemo1"/>
                </findby>
            </usesport>
        </connectinterface>
    </connections>
</softwareassembly>

=== ClausKlein/OSSIE/waveforms/pass_data_waveform/pass_data_waveform.sad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareassembly SYSTEM "../../xml/dtd/softwareassembly.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softwareassembly id="DCE:e61898c6-3629-11dc-a997-00123f573a7f" name="OSSIE::pass_data_waveform">
    <componentfiles>
        <componentfile id="pass_data_c8d997ce-3629-11dc-875d-00123f573a7f" type="SPD">
            <localfile name="xml/pass_data/pass_data.spd.xml"/>
        </componentfile>
    </componentfiles>
    <partitioning>
        <componentplacement>
            <componentfileref refid="pass_data_c8d997ce-3629-11dc-875d-00123f573a7f"/>
            <componentinstantiation id="DCE:cfe19774-3629-11dc-843c-00123f573a7f">
                <usagename>pass_data</usagename> 
                <findcomponent>
                    <namingservice name="DomainName1/pass_data"/>
                </findcomponent>
            </componentinstantiation>
        </componentplacement>
    </partitioning>
    <assemblycontroller>
        <componentinstantiationref refid="DCE:cfe19774-3629-11dc-843c-00123f573a7f"/>
    </assemblycontroller>
    <connections>
    </connections>
</softwareassembly>
