=== ClausKlein/OSSIE/platform/dtd/softpkg.dtd
<!ELEMENT softpkg
      ( title?
	, author+
	, description?
	, propertyfile?
	, descriptor?
	, implementation+
	, usesdevice*
	)>
<!ATTLIST softpkg
	id		ID	#REQUIRED
	name		CDATA	#REQUIRED
	type		(sca_compliant | sca_non_compliant)  "sca_compliant"
	version	CDATA	#IMPLIED >

<!ELEMENT localfile EMPTY>
<!ATTLIST localfile
	name		CDATA	#REQUIRED>

<!ELEMENT propertyfile
	(localfile
	)>
<!ATTLIST propertyfile
	type		CDATA	#IMPLIED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT pkgtype (#PCDATA)>

<!ELEMENT author 
	( name*
	, company?
	, webpage?
	)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT company (#PCDATA)>

<!ELEMENT webpage (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT descriptor
	(localfile
	)>
<!ATTLIST descriptor
	name		CDATA	#IMPLIED>

<!ELEMENT implementation
	( description?
	, propertyfile?
	, code
	, compiler?
	, programminglanguage?
	, humanlanguage?
	, runtime?
	, ( os
	  | processor
	  | dependency
	  )+
	, usesdevice*
	)>

<!ATTLIST implementation
	id		ID	#REQUIRED
	aepcompliance (aep_compliant | aep_non_compliant) "aep_compliant">

<!ELEMENT code 
	( localfile
	, entrypoint?
	, stacksize?
	, priority?
	)>
<!ATTLIST code
	type		CDATA	#IMPLIED>

<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT stacksize (#PCDATA)>

<!ELEMENT priority (#PCDATA)>

<!ELEMENT compiler EMPTY>
<!ATTLIST compiler
	name		CDATA	#REQUIRED
	version 	CDATA	#IMPLIED>

<!ELEMENT programminglanguage EMPTY>
<!ATTLIST programminglanguage
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT humanlanguage EMPTY>
<!ATTLIST humanlanguage
	name		CDATA	#REQUIRED >

<!ELEMENT os EMPTY>
<!ATTLIST os
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
	name		CDATA	#REQUIRED>

<!ELEMENT dependency
	( softpkgref
	| propertyref
	)>
<!ATTLIST dependency
	type		CDATA	#REQUIRED>

<!ELEMENT runtime EMPTY>
<!ATTLIST runtime
	name		CDATA	#REQUIRED
	version	CDATA	#IMPLIED>

<!ELEMENT propertyref EMPTY>
<!ATTLIST propertyref
	refid		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>
	
<!ELEMENT softpkgref
	( localfile
	,  implref?
	)>

<!ELEMENT implref EMPTY>
<!ATTLIST implref 
	refid		CDATA	#REQUIRED>

<!ELEMENT  usesdevice
	( propertyref+
	)>
<!ATTLIST usesdevice
	id		ID	#REQUIRED
	type		CDATA	#REQUIRED>

=== ClausKlein/OSSIE/components/AutomaticGainControl/xml/AutomaticGainControl.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="AutomaticGainControl" id="DCE:a04dc9e4-8fec-11db-a862-00123f63025f">
    <title>Automatic gain control component</title>
    <description>Automatically controls gain levels for RF and audio signals</description>
    <author>
        <name>Joseph Gaeddert</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/AutomaticGainControl/AutomaticGainControl.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/AutomaticGainControl/AutomaticGainControl.scd.xml"/>
    </descriptor>
    <implementation id="DCE:a04e9590-8fec-11db-b300-00123f63025f" aepcompliance="aep_compliant">
        <description>default implementation description</description> 
        <code type="Executable">
            <localfile name="bin/AutomaticGainControl"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/platform/Sound_out/soundCardPlayback.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softpkg id="DCE:93fe82d9-691e-422d-aaf9-bccc65b6de6d" name="soundCardPlayback" type="sca_compliant" version="">
    <title>Sound card playback device</title>
    <description />
    <author>
        <name>OSSIE Team</name>
        <company>VA Tech/MPRG</company>
        <webpage>http://ossie.mprg.org/</webpage>
    </author>
    <descriptor name="">
        <localfile name="xml/soundCardPlayback/soundCardPlayback.scd.xml" />
    </descriptor>
        <propertyfile type="PRF">
            <localfile name="xml/soundCardPlayback/soundCardPlayback.prf.xml" />
        </propertyfile>
    <!--[Implementation Sound_out_linux]-->
    <implementation id="DCE:4b903f0e-0c2c-401b-89fc-3beaa82359f0" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="bin/soundCardPlayback" />
        </code>
        <os name="Linux" version="5.5.1" />
        <processor name="x86" />
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/pass_data/pass_data.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.2-->
<!--Powered by Python-->
<softpkg name="pass_data" id="DCE:08d3fb9a-272e-11dc-bd56-00123f573a7f">
    <title/>
    <author>
        <name>Drew Cormier</name> 
        <company>Wireless at Virginia Techi</company> 
        <webpage>http://www.wireless.vt.edu</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/pass_data/pass_data.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/pass_data/pass_data.scd.xml"/>
    </descriptor>
    <implementation id="DCE:08d4effa-272e-11dc-b933-00123f573a7f">
        <description>just passes data</description> 
        <code type="Executable">
            <localfile name="bin/pass_data.py"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/am_demod/am_demod.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.5.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="am_demod" id="DCE:ac6ee9de-e6df-4019-b5d9-21cea4a39e9f">
    <title/>
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/am_demod/am_demod.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/am_demod/am_demod.scd.xml"/>
    </descriptor>
    <implementation id="DCE:ac6ee9de-e6df-4019-b5d9-21cea4a39e9f" aepcompliance="aep_compliant">
        <description>Default Description</description> 
        <code type="Executable">
            <localfile name="bin/am_demod"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/platform/GPP/GPP.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softpkg id="DCE:6be771f4-4ce3-4b4c-9e7c-10e88eeece7f" name="GPP" type="sca_compliant" version="">
    <title />
    <description>General purpose processor device</description>
    <author>
        <name>Philip Balister</name>
        <company>MPRG</company>
        <webpage>www.mprg.org</webpage>
    </author>
    <descriptor name="">
        <localfile name="xml/GPP/GPP.scd.xml" />
    </descriptor>
    <!--[Implementation GPP_linux]-->
    <implementation id="DCE:0ef71fab-731d-4ee1-a528-a6da2207e0c5" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="bin/GPP" />
        </code>
        <compiler name="gcc" version="3.4" />
        <humanlanguage name="english" />
        <os name="Linux" version="5.5.1" />
        <processor name="x86" />
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/amplifier/amplifier.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="amplifier" id="DCE:4411cf24-7a55-11db-9ed5-00123f573a7f">
    <title>amplifier component version 0.6.2</title>
    <description>amplifier with independent integer I and Q gains, v0.6.2</description>
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/amplifier/amplifier.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/amplifier/amplifier.scd.xml"/>
    </descriptor>
    <implementation id="DCE:4412b5ce-7a55-11db-9545-00123f573a7f" aepcompliance="aep_compliant">
        <description>Default Description</description> 
        <code type="Executable">
            <localfile name="bin/amplifier"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/components/JPEG_VideoViewer/JPEG_VideoViewer.spd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--Created with OSSIE WaveDev Beta Version 0.6.0b-->
<!--Powered by Python-->
<softpkg type="sca_compliant" name="JPEG_VideoViewer" id="DCE:bd3f85ee-c11d-11db-96e1-000129227a88">
    <title/>
    <author>
        <name>OSSIE Project</name> 
        <company>Mobile and Portable Radio Research Group</company> 
        <webpage>http://www.mprg.org</webpage> 
    </author>
    <propertyfile type="PRF">
        <localfile name="xml/JPEG_VideoViewer/JPEG_VideoViewer.prf.xml"/>
    </propertyfile>
    <descriptor>
        <localfile name="xml/JPEG_VideoViewer/JPEG_VideoViewer.scd.xml"/>
    </descriptor>
    <implementation id="DCE:bd403480-c11d-11db-85bb-000129227a88" aepcompliance="aep_compliant">
        <description>Default Description</description> 
        <code type="Executable">
            <localfile name="bin/JPEG_VideoViewer"/>
        </code>
        <processor name="x86"/>
    </implementation>
</softpkg>

=== ClausKlein/OSSIE/platform/Sound_in/soundCardCapture.spd.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softpkg SYSTEM "../dtd/softpkg.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softpkg id="DCE:f171d2db-0e8f-4a82-a687-19f76a64c079" name="soundCardCapture" type="sca_compliant" version="">
    <title />
    <description>This device uses ALSA (www.alsa-project.org) to capture audio from the sound card</description>
    <author>
        <name>OSSIE Team</name>
        <company>VA Tech/MPRG</company>
        <webpage>http://ossie.mprg.org/</webpage>
    </author>
    <descriptor name="">
	    <localfile name="xml/soundCardCapture/soundCardCapture.scd.xml" />
    </descriptor>
    <propertyfile type="PRF">
  	    <localfile name="xml/soundCardCapture/soundCardCapture.prf.xml" />
    </propertyfile>
    <!--[Implementation Sound_in_linux]-->
    <implementation id="DCE:cfbeaba2-026c-46bd-98db-7f86ff80030d" aepcompliance="aep_compliant">
        <code type="Executable">
            <localfile name="bin/soundCardCapture" />
        </code>
        <os name="Linux" version="5.5.1" />
        <processor name="x86" />
    </implementation>
</softpkg>
